executor: local
use-singularity: true
singularity-args: "-B {WORKDIR}:/mnt -B {WORKDIR}/tmp:/tmp --pwd /mnt --no-home --writable"
latency-wait: 30
show-failed-logs: True
keep-going: False
printshellcmds: True
rerun-incomplete: True

set-threads:
  all: 1
  run_mitos2: 1
  run_cpgavas2: 1
  run_chloe: 1
  create_hash: 1
  run_novoplasty: 1
  run_mitohifi: 8
  get_assemblies: 1
  check_shortreads_files: 1
  check_longreads_files: 1
  check_adapters: 1
  check_nhmmer_db: 1
  extract_table2asn: 1
  index_hmmer_db: 1
  run_bwa_index: 1
  run_bwa_mem: 4
  run_samtools_index: 1
  run_pilon: 2
  write_genbank_mitos2: 1
  write_genbank_chloe: 1
  write_genbank_cpgavas2: 1
  rotate_mito_genbanks: 1
  rotate_cpgavas_genbanks: 1
  rotate_chloe_genbanks: 1
  get_genbank_fastas: 1
  run_blastn: 1
  run_recruitment_plot: 1
  run_bwa_index_rotated: 1
  run_bwa_mem_rotated: 4
  run_samtools_depth: 1
  run_samtools_depth_rotated: 1
  run_depth_plot: 1
  run_ogdraw_mito: 1
  run_ogdraw_chloro: 1
  get_mito_ncRNA_sequences_short: 1
  run_ncRNA_nhmmer_short: 4
  get_mito_intergenes_sequences_short: 1
  run_intergenes_nhmmer_short: 4
  get_mito_ncRNA_sequences_long: 1
  run_ncRNA_nhmmer_long: 4
  get_mito_intergenes_sequences_long: 1
  run_intergenes_nhmmer_long: 4
  get_chloro_intergenes_sequences: 1
  run_intergenes_nhmmer_chloro: 4
  get_chloro_ncRNA_sequences: 1
  run_ncRNA_nhmmer_chloro: 4
  run_fastp: 4
  check_reference: 1

set-resources:
  all:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_mitos2:
    mem_mb: 8000
    runtime: 4320
    node: 1
  run_cpgavas2:
    mem_mb: 8000
    runtime: 4320
    node: 1
  run_chloe:
    mem_mb: 8000
    runtime: 4320
    node: 1
  create_hash:
    mem_mb: 50000
    runtime: 4320
    node: 1
  run_novoplasty:
    mem_mb: 50000
    runtime: 4320
    node: 1
  run_mitohifi:
    mem_mb: 50000
    runtime: 4320
    node: 1
  get_assemblies:
    mem_mb: 1000
    runtime: 4320
    node: 1
  check_shortreads_files:
    mem_mb: 1000
    runtime: 4320
    node: 1
  check_longreads_files:
    mem_mb: 1000
    runtime: 4320
    node: 1
  check_adapters:
    mem_mb: 1000
    runtime: 4320
    node: 1
  check_reference:
    mem_mb: 1000
    runtime: 4320
    node:
  check_nhmmer_db:
    mem_mb: 1000
    runtime: 4320
    node: 1
  extract_table2asn:
    mem_mb: 1000
    runtime: 4320
    node: 1
  index_hmmer_db:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_bwa_index:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_bwa_mem:
    mem_mb: 10000
    runtime: 4320
    node: 1
  run_samtools_index:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_pilon:
    mem_mb: 80000
    runtime: 4320
    node: 1
  write_genbank_mitos2:
    mem_mb: 1000
    runtime: 4320
    node: 1
  write_genbank_chloe:
    mem_mb: 1000
    runtime: 4320
    node: 1
  write_genbank_cpgavas2:
    mem_mb: 1000
    runtime: 4320
    node: 1
  rotate_mito_genbanks:
    mem_mb: 1000
    runtime: 4320
    node: 1
  rotate_cpgavas_genbanks:
    mem_mb: 1000
    runtime: 4320
    node: 1
  rotate_chloe_genbanks:
    mem_mb: 1000
    runtime: 4320
    node: 1
  get_genbank_fastas:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_blastn:
    mem_mb: 50000
    runtime: 4320
    node: 1
  run_recruitment_plot:
    mem_mb: 50000
    runtime: 4320
    node: 1
  run_bwa_index_rotated:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_bwa_mem_rotated:
    mem_mb: 50000
    runtime: 4320
    node: 1
  run_samtools_depth:
    mem_mb: 2000
    runtime: 4320
    node: 1
  run_samtools_depth_rotated:
    mem_mb: 2000
    runtime: 4320
    node: 1
  run_depth_plot:
    mem_mb: 2000
    runtime: 4320
    node: 1
  run_ogdraw_mito:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_ogdraw_chloro:
    mem_mb: 1000
    runtime: 4320
    node: 1
  get_mito_ncRNA_sequences_short:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_ncRNA_nhmmer_short:
    mem_mb: 8000
    runtime: 4320
    node: 1
  get_mito_intergenes_sequences_short:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_intergenes_nhmmer_short:
    mem_mb: 8000
    runtime: 4320
    node: 1
  get_mito_ncRNA_sequences_long:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_ncRNA_nhmmer_long:
    mem_mb: 8000
    runtime: 4320
    node: 1
  get_mito_intergenes_sequences_long:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_intergenes_nhmmer_long:
    mem_mb: 8000
    runtime: 4320
    node: 1
  get_chloro_intergenes_sequences:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_intergenes_nhmmer_chloro:
    mem_mb: 8000
    runtime: 4320
    node: 1
  get_chloro_ncRNA_sequences:
    mem_mb: 1000
    runtime: 4320
    node: 1
  run_ncRNA_nhmmer_chloro:
    mem_mb: 8000
    runtime: 4320
    node: 1
  run_fastp:
    mem_mb: 4000
    runtime: 4320
    node: 1
